# Introduction to NumPy

# NumPy Arrays

In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [5]:
nestedlist=[[1,2], [3,4], [5,6]]
nestedlist

[[1, 2], [3, 4], [5, 6]]

In [6]:
np.array(nestedlist)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [26]:
np.random.rand(2)

array([0.19802316, 1.41501031])

In [27]:
np.random.rand(3,5)

array([[0.81712698, 0.59378911, 0.9181364 , 0.68360034, 0.92570774],
       [0.25581412, 0.52824273, 0.78551175, 0.60742127, 0.46425402],
       [0.01131358, 0.92753716, 0.82203077, 0.16094619, 0.87836481]])

In [28]:
np.random.rand(3,5)*10

array([[6.97456771, 8.4438226 , 3.4233566 , 2.48580715, 3.37822553],
       [0.66576576, 7.52105925, 4.95880686, 1.54372248, 5.01608986],
       [2.63257711, 0.99029541, 2.18251622, 9.39575363, 0.91034586]])

In [29]:
np.random.randn(3,5)

array([[ 2.24752618, -0.12562862,  0.38785578,  0.58963944, -0.39359224],
       [-0.65751985, -0.61460717,  1.40236716,  0.71031744,  0.86351014],
       [-0.35122603, -1.24501627, -1.21149327,  0.5893165 , -1.11118221]])

In [33]:
np.random.randint(0,10,(2,7))

array([[8, 1, 0, 7, 5, 9, 0],
       [7, 5, 0, 0, 4, 4, 7]])

In [36]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr=np.random.randint(0,50,10)
ranarr

array([21, 43, 24, 48, 26, 41, 27, 15, 14, 46])

In [50]:
ranarr.max()

48

In [51]:
ranarr.argmax()

3

In [52]:
ranarr.mean()

30.5

In [53]:
ranarr.dtype

dtype('int32')

# NumPy Index Selection

In [55]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[8]

8

In [57]:
arr[3:5]

array([3, 4])

In [58]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [59]:
arr[:5:2]

array([0, 2, 4])

In [60]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [71]:
#it affecting to the original array
arr=np.arange(0,11)
print(arr)
slice_of_array=arr[0:5]
print(slice_of_array)

slice_of_array[:]=99
print(slice_of_array)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[99 99 99 99 99]
[99 99 99 99 99  5  6  7  8  9 10]


In [72]:
arr=np.arange(0,11)
print(arr)
slice_of_array=arr[0:5].copy()
print(slice_of_array)

slice_of_array[:]=99
print(slice_of_array)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[99 99 99 99 99]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [73]:
arr_2d=np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
arr_2d.shape

(3, 3)

In [75]:
arr_2d[0]

array([ 5, 10, 15])

In [76]:
arr_2d[1][1]

25

In [78]:
arr_2d[1,1]

25

In [79]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [80]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [81]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [84]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# Numpy Operations

In [87]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [89]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [90]:
arr/arr

c:\users\user\anaconda3\envs\mytfenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [91]:
1/0

ZeroDivisionError: division by zero

In [92]:
1/arr

c:\users\user\anaconda3\envs\mytfenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [93]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [94]:
np.log(arr)

c:\users\user\anaconda3\envs\mytfenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [95]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [96]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
arr.sum()

45

In [98]:
arr.mean()

4.5

In [99]:
arr.max()

9

In [100]:
arr.std()

2.8722813232690143

In [101]:
arr.var()

8.25

In [103]:
arr_2d=np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
arr_2d.sum()

300

In [106]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [107]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])